spring:
  application:
    name: Jetbrains-Help
  thymeleaf:
    cache: false
server:
  port: 10768
help:
  default-license-name: Are_You_OK
  default-assignee-name: Im_Fine_Thank_You
  default-expiry-date: 2099-12-31
